// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Assets.Libs.Config
{
    public sealed class GlobalSettingFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Assets.Libs.Config.GlobalSetting>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Assets.Libs.Config.GlobalSetting value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.Language>(formatterResolver).Serialize(ref writer, value.curLanguage, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.PlayMode>(formatterResolver).Serialize(ref writer, value.curPlayMode, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.Theme>(formatterResolver).Serialize(ref writer, value.curTheme, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.FoodSprite>(formatterResolver).Serialize(ref writer, value.curFoodSprite, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.SnakeSprite>(formatterResolver).Serialize(ref writer, value.curSnakeSprite, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.FontStyle>(formatterResolver).Serialize(ref writer, value.curFontStyle, options);
        }

        public global::Assets.Libs.Config.GlobalSetting Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Assets.Libs.Config.GlobalSetting();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.curLanguage = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.Language>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.curPlayMode = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.PlayMode>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.curTheme = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.Theme>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.curFoodSprite = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.FoodSprite>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.curSnakeSprite = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.SnakeSprite>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.curFontStyle = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Assets.Libs.Enum.FontStyle>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
