// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(10)
            {
                { typeof(global::System.Collections.Generic.List<global::Assets.Libs.Config.Record>), 0 },
                { typeof(global::Assets.Libs.Enum.FontStyle), 1 },
                { typeof(global::Assets.Libs.Enum.FoodSprite), 2 },
                { typeof(global::Assets.Libs.Enum.Language), 3 },
                { typeof(global::Assets.Libs.Enum.PlayMode), 4 },
                { typeof(global::Assets.Libs.Enum.SnakeSprite), 5 },
                { typeof(global::Assets.Libs.Enum.Theme), 6 },
                { typeof(global::Assets.Libs.Config.Config), 7 },
                { typeof(global::Assets.Libs.Config.GlobalSetting), 8 },
                { typeof(global::Assets.Libs.Config.Record), 9 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ListFormatter<global::Assets.Libs.Config.Record>();
                case 1: return new MessagePack.Formatters.Assets.Libs.Enum.FontStyleFormatter();
                case 2: return new MessagePack.Formatters.Assets.Libs.Enum.FoodSpriteFormatter();
                case 3: return new MessagePack.Formatters.Assets.Libs.Enum.LanguageFormatter();
                case 4: return new MessagePack.Formatters.Assets.Libs.Enum.PlayModeFormatter();
                case 5: return new MessagePack.Formatters.Assets.Libs.Enum.SnakeSpriteFormatter();
                case 6: return new MessagePack.Formatters.Assets.Libs.Enum.ThemeFormatter();
                case 7: return new MessagePack.Formatters.Assets.Libs.Config.ConfigFormatter();
                case 8: return new MessagePack.Formatters.Assets.Libs.Config.GlobalSettingFormatter();
                case 9: return new MessagePack.Formatters.Assets.Libs.Config.RecordFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
